name: build-test.yml
on:
  pull_request:
    branches:
      - master

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'corretto'

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check Lint
        run: ./gradlew ktlintCheck
  test:
    needs: check-lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run test
        run: ./gradlew test
